### ISSUE TITLE
how to work with thrift version 2?

### ISSUE THREAD

**Issue by Paulswith** [midnightexigent/hbase-thrift-rs#1]
Hi, Thank you for contributing a great repo.

In my case, I start HBase with thrift2, with Compact-protocol and Buffered-transport

then I write below code to try to connect it but give me an error
```rust 
	let mut channel = TTcpChannel::new();
	channel.open("localhost:9090")?;
	let (in_chan, out_chan) = channel.split()?;
	// let server_type = TThriftServerType::from(2);
	let in_prot = TCompactInputProtocol::new(TBufferedReadTransport::new(in_chan));
	let out_prot = TCompactOutputProtocol::new(TBufferedWriteTransport::new(out_chan));

	let mut client = HbaseSyncClient::new(in_prot, out_prot);
	let t= client.get_thrift_server_type()?;
	println!("{:?}", t);
	let tables = client.get_table_names()?;
	tables.iter().for_each(|v| println!("{:?}", v));
```

```text

TThriftServerType(2) 
Error: ApplicationError { kind: UnknownMethod, message: "Invalid method name: 'getTableNames'" }
```

I also try others client method but still shown me same error.
And I confirm my HBase works ok,  I use python hbase client can connect it and works.

Thanks in advance

**Comment by midnightexigent** [comment]
This client isn't generated from the [thrift2](https://github.com/apache/hbase/tree/master/hbase-thrift/src/main/resources/org/apache/hadoop/hbase/thrift2) spec. So I am not surprised it doesn't work

I was counting on making one in a separate crate `hbase-thrift2` but never got around to actually doing it

**Comment by Paulswith** [comment]
Thanks u reply. I look some hbase document, and know how to build rust code from hbase.thrift. It works for me after follow below steps:

get hbase.thrift from apache-hbase repo:

**Comment by Paulswith** [comment]
Thanks u reply. I look some hbase document, and know how to build rust code from hbase.thrift. It works for me after follow below steps:

**Comment by Paulswith** [comment]
Thanks u reply. I look some hbase document, and know how to build rust code from hbase.thrift. It works for me after follow below steps:

1. get hbase.thrift from [repo](https://raw.githubusercontent.com/apache/hbase/master/hbase-thrift/src/main/resources/org/apache/hadoop/hbase/thrift2/hbase.thrift)
2. `thrift -gen rs ./hbase.thrift`
